### PR TITLE
Fix: platform detection for CentOS7

### PR DESCRIPTION
**Pull request by prashantmital**
#161

### CODE REVIEW

**Comment by prashantmital** [comment]
@cournape: are we waiting for something on this? Is there something you would like for me to change?

**Comment by cournape** [comment]
I'd like to have a test, and maybe change the string manipulation into a regex to be more flexible (I suspect other centos versions will break this code again)

**Comment by prashantmital** [comment]
Ok. I will leave this open for the time being in that case.

**Comment by prashantmital** [comment]
@cournape:This fix ties into issue #164 but does NOT fix it for the RHEL case. 
Good call on waiting on the merge.

**Comment by prashantmital** [comment]
Closing stale PR. Issue is still open AFAIK.

**Pull request closed without merging**
