### PR TITLE
TST: update test data runtimes to include symlinks

### PR DESCRIPTION
**Pull request by johntyree**
The dummy runtimes don't include symlinks, which are important to test. This adds them.

I think I've done this correctly... but what is "correct" really when referring to software? :pensive: :thought_balloon:

### CODE REVIEW

**Comment by johntyree** [comment]
Should these include `pyc` files?

**Comment by johntyree** [comment]
@cournape a lot of updates here. Very tedious. Let's hope it never needs to be done again.

Each platform has a dummy runtime for each python (279, 2710, 341, 351) with some symlinks and cached / optimized files added to each.

**Comment by johntyree** [comment]
In addition to what's here, the `python.exe` executable in `cpython-2.7.9+1-win_x86-msvc2008.runtime` outputs `2.7.10` instead of `2.7.9`, which breaks tests. It looks like a compiled executable, so I'm not really sure how you made it.

**Comment by johntyree** [comment]
It's also 32bit, but that's neither here nor there.

**Comment by cournape** [comment]
@johntyree did you update the `python.exe` as well ? Looks like I never pushed the .c file used to produce the .exe (it is a trivial hello world-like program)

**Comment by johntyree** [comment]
I copied the `python.exe` from the runtime for the other arch.

**Comment by cournape** [comment]
so a win-64 has a 32 bits exec or vice et versa ?

**Comment by johntyree** [comment]
Yes, but I believe that was already the case, which is why I assumed it didn't matter. If it does, we'll have to go through and check them all to make sure

**Comment by cournape** [comment]
Let's do that in a separate PR then

**Comment by johntyree** [comment]
To be clearn, I'm now adding some of the original runtimes, without pyc files, back and renaming them both to reflect the difference. Is that what you intended?

**Comment by cournape** [comment]
What do you want to rename exactly ? (one cannot rename the actual runtime files)

**Comment by johntyree** [comment]
Oh. I was suggesting renaming the files, yes. How do you propose we differentiate between files with pyc in them and files without? Separate dirs will also work fine.

**Comment by johntyree** [comment]
Until we fix the `python.exe` files, they ouptut the following wrong or missing stuff.

```
$ find . -name "python.exe" | sort -V -k 2 -t - | while read line; do echo  "$line"; wine ./$line; echo ; done                             
./cpython-2.7.9+1-win_x86-msvc2008.runtime/python.exe
2.7.9

./cpython-2.7.9+1-win_x86_64-msvc2008.runtime/python.exe
2.7.10

./cpython-2.7.10+1-win_x86-msvc2008.runtime/python.exe
2.7.10

./cpython-2.7.10+1-win_x86_64-msvc2008.runtime/python.exe

./cpython-3.4.1+1-win_x86-msvc2008.runtime/python.exe

./cpython-3.4.1+1-win_x86_64-msvc2008.runtime/python.exe

./cpython-3.5.1+1-win_x86-msvc2008.runtime/python.exe

./cpython-3.5.1+1-win_x86_64-msvc2008.runtime/python.exe
```

**Comment by johntyree** [comment]
```
.
./cpython-2.7.9+1-osx_x86_64-darwin.runtime
./cpython-2.7.9+1-osx_x86_64-darwin.runtime/bin
./cpython-2.7.9+1-osx_x86_64-darwin.runtime/bin/python
./cpython-2.7.9+1-osx_x86_64-darwin.runtime/bin/python2
./cpython-2.7.9+1-osx_x86_64-darwin.runtime/bin/python2.7
./cpython-2.7.9+1-osx_x86_64-darwin.runtime/enthought
./cpython-2.7.9+1-osx_x86_64-darwin.runtime/enthought/runtime.json
./cpython-2.7.9+1-osx_x86_64-darwin.runtime/lib
./cpython-2.7.9+1-osx_x86_64-darwin.runtime/lib/python2.7
./cpython-2.7.9+1-osx_x86_64-darwin.runtime/lib/python2.7/custom_tools
./cpython-2.7.9+1-osx_x86_64-darwin.runtime/lib/python2.7/custom_tools/fix-scripts.py
./cpython-2.7.9+1-osx_x86_64-darwin.runtime/lib/python2.7/site-packages
./cpython-2.7.9+1-rh5_x86_64-gnu.runtime
./cpython-2.7.9+1-rh5_x86_64-gnu.runtime/bin
./cpython-2.7.9+1-rh5_x86_64-gnu.runtime/bin/python
./cpython-2.7.9+1-rh5_x86_64-gnu.runtime/bin/python2
./cpython-2.7.9+1-rh5_x86_64-gnu.runtime/bin/python2.7
./cpython-2.7.9+1-rh5_x86_64-gnu.runtime/enthought
./cpython-2.7.9+1-rh5_x86_64-gnu.runtime/enthought/runtime.json
./cpython-2.7.9+1-rh5_x86_64-gnu.runtime/lib
./cpython-2.7.9+1-rh5_x86_64-gnu.runtime/lib/python2.7
./cpython-2.7.9+1-rh5_x86_64-gnu.runtime/lib/python2.7/custom_tools
./cpython-2.7.9+1-rh5_x86_64-gnu.runtime/lib/python2.7/custom_tools/fix-scripts.py
./cpython-2.7.9+1-rh5_x86_64-gnu.runtime/lib/python2.7/site-packages
./cpython-2.7.9+1-win_x86-msvc2008.runtime
./cpython-2.7.9+1-win_x86-msvc2008.runtime/Lib
./cpython-2.7.9+1-win_x86-msvc2008.runtime/Lib/custom_tools
./cpython-2.7.9+1-win_x86-msvc2008.runtime/Lib/custom_tools/fix-scripts.py
./cpython-2.7.9+1-win_x86-msvc2008.runtime/Lib/custom_tools/py_info.dat
./cpython-2.7.9+1-win_x86-msvc2008.runtime/Lib/custom_tools/py_version.dat
./cpython-2.7.9+1-win_x86-msvc2008.runtime/Lib/custom_tools/site.py
./cpython-2.7.9+1-win_x86-msvc2008.runtime/Lib/custom_tools/__init__.py
./cpython-2.7.9+1-win_x86-msvc2008.runtime/enthought
./cpython-2.7.9+1-win_x86-msvc2008.runtime/enthought/runtime.json
./cpython-2.7.9+1-win_x86-msvc2008.runtime/python.exe
./cpython-2.7.9+1-win_x86_64-msvc2008.runtime
./cpython-2.7.9+1-win_x86_64-msvc2008.runtime/Lib
./cpython-2.7.9+1-win_x86_64-msvc2008.runtime/Lib/custom_tools
./cpython-2.7.9+1-win_x86_64-msvc2008.runtime/Lib/custom_tools/fix-scripts.py
./cpython-2.7.9+1-win_x86_64-msvc2008.runtime/Lib/custom_tools/py_info.dat
./cpython-2.7.9+1-win_x86_64-msvc2008.runtime/Lib/custom_tools/py_version.dat
./cpython-2.7.9+1-win_x86_64-msvc2008.runtime/Lib/custom_tools/site.py
./cpython-2.7.9+1-win_x86_64-msvc2008.runtime/Lib/custom_tools/__init__.py
./cpython-2.7.9+1-win_x86_64-msvc2008.runtime/enthought
./cpython-2.7.9+1-win_x86_64-msvc2008.runtime/enthought/runtime.json
./cpython-2.7.9+1-win_x86_64-msvc2008.runtime/python.exe
./cpython-2.7.9+2-rh5_x86_64-gnu.runtime
./cpython-2.7.9+2-rh5_x86_64-gnu.runtime/enthought
./cpython-2.7.9+2-rh5_x86_64-gnu.runtime/enthought/runtime.json
./cpython-2.7.10+1-osx_x86_64-darwin.runtime
./cpython-2.7.10+1-osx_x86_64-darwin.runtime/bin
./cpython-2.7.10+1-osx_x86_64-darwin.runtime/bin/python
./cpython-2.7.10+1-osx_x86_64-darwin.runtime/bin/python2
./cpython-2.7.10+1-osx_x86_64-darwin.runtime/bin/python2.7
./cpython-2.7.10+1-osx_x86_64-darwin.runtime/enthought
./cpython-2.7.10+1-osx_x86_64-darwin.runtime/enthought/runtime.json
./cpython-2.7.10+1-osx_x86_64-darwin.runtime/lib
./cpython-2.7.10+1-osx_x86_64-darwin.runtime/lib/python2.7
./cpython-2.7.10+1-osx_x86_64-darwin.runtime/lib/python2.7/custom_tools
./cpython-2.7.10+1-osx_x86_64-darwin.runtime/lib/python2.7/custom_tools/fix-scripts.py
./cpython-2.7.10+1-osx_x86_64-darwin.runtime/lib/python2.7/site-packages
./cpython-2.7.10+1-rh5_x86_64-gnu.runtime
./cpython-2.7.10+1-rh5_x86_64-gnu.runtime/bin
./cpython-2.7.10+1-rh5_x86_64-gnu.runtime/bin/python
./cpython-2.7.10+1-rh5_x86_64-gnu.runtime/bin/python2
./cpython-2.7.10+1-rh5_x86_64-gnu.runtime/bin/python2.7
./cpython-2.7.10+1-rh5_x86_64-gnu.runtime/enthought
./cpython-2.7.10+1-rh5_x86_64-gnu.runtime/enthought/runtime.json
./cpython-2.7.10+1-rh5_x86_64-gnu.runtime/lib
./cpython-2.7.10+1-rh5_x86_64-gnu.runtime/lib/python2.7
./cpython-2.7.10+1-rh5_x86_64-gnu.runtime/lib/python2.7/custom_tools
./cpython-2.7.10+1-rh5_x86_64-gnu.runtime/lib/python2.7/custom_tools/fix-scripts.py
./cpython-2.7.10+1-rh5_x86_64-gnu.runtime/lib/python2.7/site-packages
./cpython-2.7.10+1-win_x86-msvc2008.runtime
./cpython-2.7.10+1-win_x86-msvc2008.runtime/Lib
./cpython-2.7.10+1-win_x86-msvc2008.runtime/Lib/custom_tools
./cpython-2.7.10+1-win_x86-msvc2008.runtime/Lib/custom_tools/fix-scripts.py
./cpython-2.7.10+1-win_x86-msvc2008.runtime/Lib/custom_tools/py_info.dat
./cpython-2.7.10+1-win_x86-msvc2008.runtime/Lib/custom_tools/py_version.dat
./cpython-2.7.10+1-win_x86-msvc2008.runtime/Lib/custom_tools/site.py
./cpython-2.7.10+1-win_x86-msvc2008.runtime/Lib/custom_tools/__init__.py
./cpython-2.7.10+1-win_x86-msvc2008.runtime/enthought
./cpython-2.7.10+1-win_x86-msvc2008.runtime/enthought/runtime.json
./cpython-2.7.10+1-win_x86-msvc2008.runtime/python.exe
./cpython-2.7.10+1-win_x86_64-msvc2008.runtime
./cpython-2.7.10+1-win_x86_64-msvc2008.runtime/Lib
./cpython-2.7.10+1-win_x86_64-msvc2008.runtime/Lib/custom_tools
./cpython-2.7.10+1-win_x86_64-msvc2008.runtime/Lib/custom_tools/fix-scripts.py
./cpython-2.7.10+1-win_x86_64-msvc2008.runtime/Lib/custom_tools/py_info.dat
./cpython-2.7.10+1-win_x86_64-msvc2008.runtime/Lib/custom_tools/py_version.dat
./cpython-2.7.10+1-win_x86_64-msvc2008.runtime/Lib/custom_tools/site.py
./cpython-2.7.10+1-win_x86_64-msvc2008.runtime/Lib/custom_tools/__init__.py
./cpython-2.7.10+1-win_x86_64-msvc2008.runtime/enthought
./cpython-2.7.10+1-win_x86_64-msvc2008.runtime/enthought/runtime.json
./cpython-2.7.10+1-win_x86_64-msvc2008.runtime/python.exe
./cpython-3.4.1+1-osx_x86_64-darwin.runtime
./cpython-3.4.1+1-osx_x86_64-darwin.runtime/bin
./cpython-3.4.1+1-osx_x86_64-darwin.runtime/bin/python
./cpython-3.4.1+1-osx_x86_64-darwin.runtime/bin/python3
./cpython-3.4.1+1-osx_x86_64-darwin.runtime/bin/python3.4
./cpython-3.4.1+1-osx_x86_64-darwin.runtime/enthought
./cpython-3.4.1+1-osx_x86_64-darwin.runtime/enthought/runtime.json
./cpython-3.4.1+1-osx_x86_64-darwin.runtime/lib
./cpython-3.4.1+1-osx_x86_64-darwin.runtime/lib/python3.4
./cpython-3.4.1+1-osx_x86_64-darwin.runtime/lib/python3.4/custom_tools
./cpython-3.4.1+1-osx_x86_64-darwin.runtime/lib/python3.4/custom_tools/fix-scripts.py
./cpython-3.4.1+1-osx_x86_64-darwin.runtime/lib/python3.4/site-packages
./cpython-3.4.1+1-rh5_x86_64-gnu.runtime
./cpython-3.4.1+1-rh5_x86_64-gnu.runtime/bin
./cpython-3.4.1+1-rh5_x86_64-gnu.runtime/bin/python
./cpython-3.4.1+1-rh5_x86_64-gnu.runtime/bin/python3
./cpython-3.4.1+1-rh5_x86_64-gnu.runtime/bin/python3.4
./cpython-3.4.1+1-rh5_x86_64-gnu.runtime/enthought
./cpython-3.4.1+1-rh5_x86_64-gnu.runtime/enthought/runtime.json
./cpython-3.4.1+1-rh5_x86_64-gnu.runtime/lib
./cpython-3.4.1+1-rh5_x86_64-gnu.runtime/lib/python3.4
./cpython-3.4.1+1-rh5_x86_64-gnu.runtime/lib/python3.4/custom_tools
./cpython-3.4.1+1-rh5_x86_64-gnu.runtime/lib/python3.4/custom_tools/fix-scripts.py
./cpython-3.4.1+1-rh5_x86_64-gnu.runtime/lib/python3.4/site-packages
./cpython-3.4.1+1-win_x86-msvc2008.runtime
./cpython-3.4.1+1-win_x86-msvc2008.runtime/Lib
./cpython-3.4.1+1-win_x86-msvc2008.runtime/Lib/custom_tools
./cpython-3.4.1+1-win_x86-msvc2008.runtime/Lib/custom_tools/fix-scripts.py
./cpython-3.4.1+1-win_x86-msvc2008.runtime/Lib/custom_tools/py_info.dat
./cpython-3.4.1+1-win_x86-msvc2008.runtime/Lib/custom_tools/py_version.dat
./cpython-3.4.1+1-win_x86-msvc2008.runtime/Lib/custom_tools/site.py
./cpython-3.4.1+1-win_x86-msvc2008.runtime/Lib/custom_tools/__init__.py
./cpython-3.4.1+1-win_x86-msvc2008.runtime/enthought
./cpython-3.4.1+1-win_x86-msvc2008.runtime/enthought/runtime.json
./cpython-3.4.1+1-win_x86-msvc2008.runtime/python.exe
./cpython-3.4.1+1-win_x86_64-msvc2008.runtime
./cpython-3.4.1+1-win_x86_64-msvc2008.runtime/Lib
./cpython-3.4.1+1-win_x86_64-msvc2008.runtime/Lib/custom_tools
./cpython-3.4.1+1-win_x86_64-msvc2008.runtime/Lib/custom_tools/fix-scripts.py
./cpython-3.4.1+1-win_x86_64-msvc2008.runtime/Lib/custom_tools/py_info.dat
./cpython-3.4.1+1-win_x86_64-msvc2008.runtime/Lib/custom_tools/py_version.dat
./cpython-3.4.1+1-win_x86_64-msvc2008.runtime/Lib/custom_tools/site.py
./cpython-3.4.1+1-win_x86_64-msvc2008.runtime/Lib/custom_tools/__init__.py
./cpython-3.4.1+1-win_x86_64-msvc2008.runtime/enthought
./cpython-3.4.1+1-win_x86_64-msvc2008.runtime/enthought/runtime.json
./cpython-3.4.1+1-win_x86_64-msvc2008.runtime/python.exe
./cpython-3.5.1+1-osx_x86_64-darwin.runtime
./cpython-3.5.1+1-osx_x86_64-darwin.runtime/bin
./cpython-3.5.1+1-osx_x86_64-darwin.runtime/bin/python
./cpython-3.5.1+1-osx_x86_64-darwin.runtime/bin/python3
./cpython-3.5.1+1-osx_x86_64-darwin.runtime/bin/python3.5
./cpython-3.5.1+1-osx_x86_64-darwin.runtime/enthought
./cpython-3.5.1+1-osx_x86_64-darwin.runtime/enthought/runtime.json
./cpython-3.5.1+1-osx_x86_64-darwin.runtime/lib
./cpython-3.5.1+1-osx_x86_64-darwin.runtime/lib/python3.5
./cpython-3.5.1+1-osx_x86_64-darwin.runtime/lib/python3.5/custom_tools
./cpython-3.5.1+1-osx_x86_64-darwin.runtime/lib/python3.5/custom_tools/fix-scripts.py
./cpython-3.5.1+1-osx_x86_64-darwin.runtime/lib/python3.5/site-packages
./cpython-3.5.1+1-rh5_x86_64-gnu.runtime
./cpython-3.5.1+1-rh5_x86_64-gnu.runtime/bin
./cpython-3.5.1+1-rh5_x86_64-gnu.runtime/bin/python
./cpython-3.5.1+1-rh5_x86_64-gnu.runtime/bin/python3
./cpython-3.5.1+1-rh5_x86_64-gnu.runtime/bin/python3.5
./cpython-3.5.1+1-rh5_x86_64-gnu.runtime/enthought
./cpython-3.5.1+1-rh5_x86_64-gnu.runtime/enthought/runtime.json
./cpython-3.5.1+1-rh5_x86_64-gnu.runtime/lib
./cpython-3.5.1+1-rh5_x86_64-gnu.runtime/lib/python3.5
./cpython-3.5.1+1-rh5_x86_64-gnu.runtime/lib/python3.5/custom_tools
./cpython-3.5.1+1-rh5_x86_64-gnu.runtime/lib/python3.5/custom_tools/fix-scripts.py
./cpython-3.5.1+1-rh5_x86_64-gnu.runtime/lib/python3.5/site-packages
./cpython-3.5.1+1-win_x86-msvc2008.runtime
./cpython-3.5.1+1-win_x86-msvc2008.runtime/Lib
./cpython-3.5.1+1-win_x86-msvc2008.runtime/Lib/custom_tools
./cpython-3.5.1+1-win_x86-msvc2008.runtime/Lib/custom_tools/fix-scripts.py
./cpython-3.5.1+1-win_x86-msvc2008.runtime/Lib/custom_tools/py_info.dat
./cpython-3.5.1+1-win_x86-msvc2008.runtime/Lib/custom_tools/py_version.dat
./cpython-3.5.1+1-win_x86-msvc2008.runtime/Lib/custom_tools/site.py
./cpython-3.5.1+1-win_x86-msvc2008.runtime/Lib/custom_tools/__init__.py
./cpython-3.5.1+1-win_x86-msvc2008.runtime/enthought
./cpython-3.5.1+1-win_x86-msvc2008.runtime/enthought/runtime.json
./cpython-3.5.1+1-win_x86-msvc2008.runtime/python.exe
./cpython-3.5.1+1-win_x86_64-msvc2008.runtime
./cpython-3.5.1+1-win_x86_64-msvc2008.runtime/Lib
./cpython-3.5.1+1-win_x86_64-msvc2008.runtime/Lib/custom_tools
./cpython-3.5.1+1-win_x86_64-msvc2008.runtime/Lib/custom_tools/fix-scripts.py
./cpython-3.5.1+1-win_x86_64-msvc2008.runtime/Lib/custom_tools/py_info.dat
./cpython-3.5.1+1-win_x86_64-msvc2008.runtime/Lib/custom_tools/py_version.dat
./cpython-3.5.1+1-win_x86_64-msvc2008.runtime/Lib/custom_tools/site.py
./cpython-3.5.1+1-win_x86_64-msvc2008.runtime/Lib/custom_tools/__init__.py
./cpython-3.5.1+1-win_x86_64-msvc2008.runtime/enthought
./cpython-3.5.1+1-win_x86_64-msvc2008.runtime/enthought/runtime.json
./cpython-3.5.1+1-win_x86_64-msvc2008.runtime/python.exe
```

**Comment by johntyree** [comment]
Aaaannnndd now I've ruined all of the permissions somehow.

**Comment by johntyree** [comment]
@cournape I think we're ready here.

**Comment by cournape** [comment]
Maybe we should just have a way to at least automatically check the dummy runtimes. But that can happen in a different PR

**Comment by johntyree** [comment]
I'm not sure what you mean by automatically checking them. I'll open an issue for it if you can clarify a little.

**Comment by johntyree** [comment]
Cleared via Slack:

> David Cournapeau 09:30: I think your original PR is good to do

**Pull request merged**
